ant:
  count: 80
  alpha: 1.0
  beta: 1.25
  theta: 0.45
  q0: 0.4
  rho: 0.2

antColony:
  iterations: 1000000000
  runtime: 9min
  tauZero: 2E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 60s