instanceId: 1
iterations: 100

ant:
    count: 69
    alpha: 1.0
    beta: 2.0
    lambda: 3.0
    theta: 0.75
    q0: 0.75
    rho: 0.1

antColony:
    tauZero: 0.001
    simulatedAnnealing:
        startingTemperature: 50
        decrementFunction: 1 # Linear, Geometric, VerySlow
        decrementParameter: 0.99 # alpha or beta
        solutionAcceptance: 0 # Take best, Probability4All
        terminationCriteria: 0 # FinalTemperature
        terminationFinalTemperature: 10 # final temperature (if needed)
        terminationParameter: 0.5