ant:
  count: 20
  alpha: 1.4
  beta: 1.35
  theta: 0.54
  q0: 0.2
  rho: 0.43

antColony:
  iterations: 1000000000
  runtime: 255s
  tauZero: 1E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 45s