ant:
  count: 20
  alpha: 1.0
  beta: 1.4
  theta: 0.5
  q0: 0.4
  rho: 0.2

antColony:
  iterations: 1000000000
  runtime: 250s
  tauZero: 7E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 50s