ant:
  count: 50
  alpha: 1.0
  beta: 1.25
  theta: 0.55
  q0: 0.35
  rho: 0.15

antColony:
  iterations: 100000
  runtime: 50s
  tauZero: 1E-4
  estimateTauZero: true
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 5000
  runtime: 10s