ant:
  count: 25
  alpha: 1.5
  beta: 0.9
  theta: 0.6
  q0: 0.3
  rho: 0.4

antColony:
  iterations: 1000000000
  runtime: 6min
  tauZero: 2E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 60s