ant:
  count: 50
  alpha: 1.0
  beta: 1.25
  theta: 0.55
  q0: 0.35
  rho: 0.15

antColony:
  iterations: 2000
  runtime: 50 s
  tauZero: 1E-4
  estimateTauZero: true
  estimateLocalSearch:
    iterations: 500
    runtime: 6 s

finalLocalSearch:
  iterations: 2000
  runtime: 10 s