ant:
  count: 20
  alpha: 1.1
  beta: 1.25
  theta: 0.7
  q0: 0.4
  rho: 0.15

antColony:
  iterations: 1000000000
  runtime: 52s
  tauZero: 6E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s

finalLocalSearch:
  iterations: 2000
  runtime: 8s