ant:
  count: 20
  alpha: 1.1
  beta: 1.4
  theta: 0.35
  q0: 0.4
  rho: 0.45

antColony:
  iterations: 1000000000
  runtime: 260s
  tauZero: 1E-3
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 40s