ant:
  count: 6
  alpha: 1.1
  beta: 1.2
  theta: 0.5
  q0: 0.3
  rho: 0.5

antColony:
  iterations: 1000000000
  runtime: 230s
  tauZero: 1E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 70s