ant:
  count: 50
  alpha: 1.1
  beta: 0.9
  theta: 0.35
  q0: 0.4
  rho: 0.5

antColony:
  iterations: 1000000000
  runtime: 260s
  tauZero: 2E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 40s