ant:
    count: 20
    alpha: 1.0
    beta: 1.4
    theta: 0.5
    q0: 0.4
    rho: 0.2

antColony:
    iterations: 1000000000
    runtime: 250 s
    tauZero: 7E-5
    estimateTauZero: true
    estimateLocalSearch:
        iterations: 500
        runtime: 6 s

finalLocalSearch:
    iterations: 2000
    runtime: 50 s