ant:
  count: 15
  alpha: 1.25
  beta: 0.8
  theta: 0.7
  q0: 0.4
  rho: 0.2

antColony:
  iterations: 1000000000
  runtime: 250s
  tauZero: 2E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 50s