ant:
  count: 6
  alpha: 1.0
  beta: 1.2
  theta: 0.6
  q0: 0.4
  rho: 0.25

antColony:
  iterations: 1000000000
  runtime: 230s
  tauZero: 1E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 70s