instanceId: 1
iterations: 100

ant:
    count: 69
    alpha: 1.0
    beta: 2.0
    lambda: 3.0
    theta: 0.75
    q0: 0.75
    rho: 0.1

antColony:
    tauZero: 0.001
    simulatedAnnealing:
        startingTemperature: 100
        decrementFunction: 0 # Linear, Geometric, VerySlow,
        decrementParameter: 0.5 #  alpha / beta
        solutionAcceptance: 0 # Take best, Probability4All
        terminationCriteria: 0 # FinalTemperature, GeometricDecrement, VerySlowDecrease
        terminationFinalTemperature: 100 # final temperature (if needed)
        terminationParametar: 0.5 # alpha / beta (if needed)