ant:
  count: 30
  alpha: 1.0
  beta: 1.5
  theta: 0.4
  q0: 0.2
  rho: 0.5

antColony:
  iterations: 1000000000
  runtime: 260s
  tauZero: 1E-3
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 40s