ant:
  count: 20
  alpha: 1.15
  beta: 1.0
  theta: 0.5
  q0: 0.3
  rho: 0.35

antColony:
  iterations: 1000000000
  runtime: 50s
  tauZero: 1E-4
  estimateTauZero: true
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 5000
  runtime: 10s