instanceId: 1

ant:
    count: 69
    alpha: 1.0
    beta: 2.0
    theta: 0.75
    q0: 0.75
    rho: 0.1

antColony:
    iterations: 100
    runtimeSeconds: 120.0
    tauZero: 0.001
    estimateTauZero: true