ant:
  count: 6
  alpha: 0.9
  beta: 1.25
  theta: 0.6
  q0: 0.4
  rho: 0.2

antColony:
  iterations: 1000000000
  runtime: 14min
  tauZero: 1E-6
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 12min