ant:
  count: 25
  alpha: 1.2
  beta: 1.0
  theta: 0.4
  q0: 0.25
  rho: 0.15

antColony:
  iterations: 1000000000
  runtime: 255s
  tauZero: 1E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 45s