ant:
  count: 80
  alpha: 0.7
  beta: 1.2
  theta: 0.55
  q0: 0.2
  rho: 0.08

antColony:
  iterations: 1000000000
  runtime: 250s
  tauZero: 1E-3
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s

finalLocalSearch:
  iterations: 2000
  runtime: 50s