ant:
  count: 25
  alpha: 1.2
  beta: 1.6
  theta: 0.45
  q0: 0.3
  rho: 0.3

antColony:
  iterations: 1000000000
  runtime: 250s
  tauZero: 1E-4
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 50s