ant:
  count: 15
  alpha: 1.45
  beta: 0.9
  theta: 0.4
  q0: 0.2
  rho: 0.3

antColony:
  iterations: 1000000000
  runtime: 250s
  tauZero: 2E-5
  estimateTauZero: false
  estimateLocalSearch:
    iterations: 500
    runtime: 6s
  bestAntLocalSearch:
    iterations: 8
    runtime: 100ms

finalLocalSearch:
  iterations: 2000
  runtime: 50s